name: prmaster

on: 
    push:
        branches:
            - develop
    
jobs:
    createPullRequest:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: create pull request
              uses: peter-evans/create-pull-request@v5
              with:
                commit-message: "new pull request"
                title: 'nuevas funcionalidades de decide-part-camaron-2'
                body: 'esta pull request ha sido autogenerada por el equipo de decide-part-camaron-2'
                base: 'master'
                branch: 'develop'
